# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd3236df4672383f2dccddfacddd49d355cf91914d3ca27d307c264c1c292d845f4b8252c9d8293a91b1b952efbe90b12a81b0ca6ac4e528df6b50f79762f138

test:
  secret_key_base: 5b87f6b0af80b93d528c6430d2f964f450c5f3a76594a09e809a0c830dcbe8a3d4ef0bfcccecac4fa670395a81e4bf1622705f9a58df01f2a762ba3fcb547e44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
